development:
  access_key_id: 1MEBBKABEPBMZ4GZCSR2
  secret_access_key: oTw5OjSKjiYpLbKZSjFVrtP7nbnbWdQq714t4ybS
test:
  access_key_id: abc...
  secret_access_key: abc...
production:
  access_key_id: 1MEBBKABEPBMZ4GZCSR2
  secret_access_key: oTw5OjSKjiYpLbKZSjFVrtP7nbnbWdQq714t4ybS